merge feature/tasks
LubaRo/task-manager pull request #18
Opened 2021-10-31 14:47 UTC by LubaRo

2021-11-01 20:04 UTC, greybutton requested changes

2021-11-01 20:04 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +            color="primary" // prettier cuts line breaks if word 'primary' exists
не понял комментарий) выглядит что все ок

2021-11-01 20:04 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import AddPopup from 'components/AddPopup/AddPopup';
from 'components/AddPopup';

2021-11-01 20:04 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from 'components/EditPopup/EditPopup';
from 'components/EditPopup';

2021-11-01 20:04 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        const currentStateCards = prevState[state].cards.concat(data.items);
по неймингу. currentStateCards скорее nextStateCards or newStateCards т.е. каким будет, пока это не текущий стейт

2021-11-01 20:04 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      if (task.id) {
немного странно условие, ид после создания всегда будет

2021-11-01 20:04 UTC, greybutton commented on app/javascript/utils/fetchHelper.js
> +  delete(url, json) {
у удаления обычно нет json

2021-11-01 20:04 UTC, greybutton commented on config/routes.rb
> +  namespace :api, defaults: {format: 'json'} do
используй символы вместо строк

2021-11-01 20:04 UTC, greybutton commented on package.json
> +    "ramda": "^0.27.1",
не хватает `qs` зависимости

2021-11-02 05:28 UTC, LubaRo commented on app/javascript/components/EditPopup/EditPopup.js
> +            color="primary" // prettier cuts line breaks if word 'primary' exists
Prettier вырезал все переносы строк, но при этом ругался на max-len, я чет грешила на слово 'primary', но все оказалось проще, у настроек `max-len` и `printWidth` были разные значения, вот его и колбасило. Исправлено.

2021-11-02 06:08 UTC, greybutton approved these changes

2021-11-02 07:56 UTC, merged